invenio_theme_tugraz/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-2026 Graz University of Technology.
#
# invenio-theme-tugraz is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""invenio module for TUGRAZ theme."""

from .ext import InvenioThemeTugraz

__version__ = "4.14.0"

__all__ = ("__version__", "InvenioThemeTugraz")

invenio_theme_tugraz/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-2025 Graz University of Technology.
#
# invenio-theme-tugraz is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

"""invenio module for TUGRAZ theme."""

import secrets
import traceback
from functools import wraps
from typing import Dict

from flask import Blueprint, Flask, current_app, g, redirect, render_template, url_for
from flask_login import current_user, login_required
from invenio_rdm_records.proxies import current_rdm_records
from invenio_records_global_search.resources.serializers import (
    GlobalSearchJSONSerializer,
)
from invenio_users_resources.proxies import current_user_resources
from opensearch_dsl.utils import AttrDict

from .search import FrontpageRecordsSearch


def create_blueprint(app: Flask) -> Blueprint:
    """Create blueprint."""
    blueprint = Blueprint(
        "invenio_theme_tugraz",
        __name__,
        template_folder="templates",
        static_folder="static",
    )
    routes = app.config.get("THEME_TUGRAZ_ROUTES")

    blueprint.add_url_rule(routes["records-search"], view_func=records_search)
    blueprint.add_url_rule(routes["index"], view_func=index)
    blueprint.add_url_rule(routes["overview"], view_func=overview)

    # base case for any otherwise unhandled exception
    app.register_error_handler(Exception, default_error_handler)

    blueprint.add_app_template_filter(make_dict_like)
    blueprint.add_app_template_filter(cast_to_dict)

    return blueprint


def records_search():
    """Search page ui.

    With this route it is possible to override the default route
    "/search" to get to the rdm-records search. The default route will
    be overriden by the global search with changing the
    SEARCH_UI_SEARCH_TEMPLATE variable to the value
    "invenio_records_global_search/search/search.html" in the
    invenio.cfg file.
    """
    return render_template("invenio_app_rdm/records/search.html")


def current_identity_is_tugraz_authenticated() -> bool:
    """Checks whether current identity has tugraz-authentication.

    NOTE: Default permission-policy has no field for `tugraz_authenticated`.
    Should the field not exist, the service checks against admin-permissions instead.
    You probably meant to configure a custom permission-policy.
    """
    rdm_service = current_rdm_records.records_service
    return rdm_service.check_permission(g.identity, "tugraz_authenticated")


def require_tugraz_authenticated_else_redirect(view_func):
    """Decorator for guarding view-functions against unauthenticated users.

    Redirects un-authenticated users to Uploads,
    where unauthenticated users are shown a message on how to get authenticated.
    """

    @wraps(view_func)
    def decorated_view(*args, **kwargs):
        if not current_identity_is_tugraz_authenticated():
            return redirect(url_for("invenio_app_rdm_users.uploads"))
        return view_func(*args, **kwargs)

    return decorated_view


def require_tugraz_authenticated_else_render(view_func):
    """Decorator for guarding view-functions against unauthenticated users.

    For unauthenticated users, renders the message on how to get authenticated.
    """

    @wraps(view_func)
    def decorated_view(*args, **kwargs):
        if not current_identity_is_tugraz_authenticated():
            url = current_user_resources.users_service.links_item_tpl.expand(
                identity=g.identity, obj=current_user
            )["avatar"]
            return render_template(
                "invenio_theme_tugraz/not_tugraz_authenticated.html",
                user_avatar=url,
            )
        return view_func(*args, **kwargs)

    return decorated_view


@login_required
def overview():
    """Overview."""
    url = current_user_resources.users_service.links_item_tpl.expand(
        g.identity, current_user
    )["avatar"]
    is_tugraz_authenticated = current_identity_is_tugraz_authenticated()
    return render_template(
        "invenio_theme_tugraz/overview.html",
        is_tugraz_authenticated=is_tugraz_authenticated,
        user_avatar=url,
    )


def make_dict_like(value: str, key: str) -> Dict[str, str]:
    """Convert the value to a dict like structure.

    in the form of a key -> value pair.
    """
    return {key: value}


def cast_to_dict(attr_dict):
    """Return the dict structure of AttrDict variable."""
    return AttrDict.to_dict(attr_dict)


def default_error_handler(e: Exception):
    """Called when an otherwise unhandled error occurs."""
    # TODO: use sentry here once it's configured
    # information we might want to log for debugging the error:
    #   - `flask.request`, a proxy to the current http-request in which the error occured
    #   - `flask.session`, a proxy to the current http-session
    #   - `e`, the passed-in exception
    # to get proxied-to objects: `flask.request._get_current_object()`

    error_id = secrets.token_hex(4)  # 4 bytes == 8 hex-chars
    tb = "".join(traceback.format_exception(e))
    msg = (
        "(caught by invenio-theme-tugraz's default_error_handler):\n"
        "Error ID: #%s\n"
        "Exception class: %s\n"
        "Exception: %s\n"
        "%s"  # NOTE: tracebacks starts with "Traceback (most recent call last):", so no need to also mention "Traceback: " explicitly here
    )
    current_app.logger.error(msg, error_id, type(e), e, tb)

    return (
        render_template(current_app.config["THEME_500_TEMPLATE"], error_id=error_id),
        500,
    )


def records_serializer(records=None):
    """Serialize list of records."""
    serializer = GlobalSearchJSONSerializer()
    return [serializer.dump_obj(r.to_dict()) for r in records]


def index():
    """Frontpage."""
    records = FrontpageRecordsSearch()[:5].sort("-created").execute()

    return render_template(
        "invenio_theme_tugraz/index.html", records=records_serializer(records)
    )


def locked(e):
    """Error page for status locked."""
    return render_template("invenio_theme_tugraz/423.html")

invenio_theme_tugraz/templates/invenio_theme_tugraz/423.html
{#
  Copyright (C) 2024 Graz University of Technology.

  invenio-theme-tugraz is free software; you can redistribute it and/or
  modify it under the terms of the MIT License; see LICENSE file for more
  details.
#}

{% extends config.THEME_ERROR_TEMPLATE %}

{% block message %}
  <h1><i class="bolt icon"></i> {{_("Locked")}}</h1>
  <p>{{_("The resource that is being accessed is locked.")}}</p>
{% endblock message %}

invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/accounts_base.html
{#
  Copyright (C) 2020-2021 Graz University of Technology.

  invenio-theme-tugraz is free software; you can redistribute it and/or
  modify it under the terms of the MIT License; see LICENSE file for more
  details.
#}

<!DOCTYPE html>
<html{% if html_css_classes %} class="{{ html_css_classes|join(' ') }}"{% endif %} lang="{{ current_i18n.locale.language|safe }}" dir="{{ current_i18n.locale.text_direction }}">
  <head>
    {%- block head %}
    {%- block head_meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {%- if description %}<meta name="description" content="{{ description }}" />{% endif %}
    {%- if keywords %}<meta name="keywords" content="{{ keywords }}" />{% endif %}
    {%- if config.get('THEME_GOOGLE_SITE_VERIFICATION', None) %}
      {%- for google_id in config.THEME_GOOGLE_SITE_VERIFICATION %}
    <meta name="google-site-verification" content="{{google_id}}"/>
      {%- endfor %}
    {%- endif %}
    {%- endblock head_meta %}
    {%- block head_title %}
    {%- set title = title or _(config.THEME_SITENAME) or _('Invenio') %}
    <title>{{title}}</title>
    {%- endblock head_title %}
    {%- block head_links %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
    {%- if keywords %}<link rel="canonical" href="{{ canonical_url }}"/>{% endif %}
    {%- block head_links_langs %}
      {%- if alternate_urls %}
        {%- for alt_ln, alternate_url in alternate_urls.items() %}
    <link rel="alternate" hreflang="{{ alt_ln }}" href="{{ alternate_url }}"/>
        {%- endfor %}
      {%- endif %}
    {%- endblock %}
    {%- block head_apple_icons %}
    {%- for size in [144, 114, 72, 57] %}
      {%- set icon_name = 'apple-touch-icon-%d-precomposed.png' | format(size) %}
    <link rel="apple-touch-icon-precomposed" sizes="{{ size }}x{{ size }}" href="{{ url_for('static', filename=icon_name) }}"/>
    {%- endfor %}
    {%- endblock head_apple_icons %}
    {%- endblock head_links %}
    {%- block header %}{% endblock header %}
    {%- block css %}
    {{ webpack['theme.css'] }}
    {{ webpack['invenio-theme-tugraz-theme.css'] }}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {%- endblock css %}
    {%- endblock head %}
  </head>
  <body ng-csp {% if body_css_classes %} class="{{ body_css_classes|join(' ') }}"{% endif %}{% if g.ln %} lang="{{ g.ln.split('_', 1)[0]|safe }}"{% if rtl_direction %} {{ rtl_direction|safe }}{% endif %}{% endif %} itemscope itemtype="http://schema.org/WebPage" data-spy="scroll" data-target=".scrollspy-target">
    {% if not config.THEME_TUGRAZ_PRODUCTION %}
    <div class="ui sticky test-instance">
      <h4>{{_ ("Test Instance") }}</h4>
      <p>{{_ ("This is the test instance of the TU Graz Repository.") }}</p>
    </div>
    {% endif %}
    {%- block body %}
    {%- block browserupgrade %}
    <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    {%- endblock browserupgrade %}
    {%- block body_inner %}

    {%- block navbar_header %}
    {%- include "invenio_theme_tugraz/navbar.html" %}
    <!--Flask messages for accounts-->
    {%- block flashmessages %}
    {%- from "invenio_theme/macros/messages.html" import flashed_messages with context -%}
    {{ flashed_messages() }}

    {%- endblock %}
    {%- endblock navbar_header %}
    
    {#
      {%- block page_header %}
      {% include config.THEME_HEADER_TEMPLATE %}
          {%- endblock page_header %}
      #}

    {%- block page_body %}
{% include "invenio_theme/body.html" %}
    {%- endblock page_body %}
    {%- endblock body_inner %}
    {%- block javascript %}
{% include config.THEME_JAVASCRIPT_TEMPLATE %}
    {%- endblock javascript %}
    {%- block trackingcode %}{% include config.THEME_TRACKINGCODE_TEMPLATE %}
    {%- endblock %}
    {%- endblock body %}
  </body>
</html>

invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/header_login.html
{%- if config.ACCOUNTS %}
  {%- if not current_user.is_authenticated %}
    {%- if config.SECURITY_REGISTERABLE %}
      <div class="short-menu-right-button">
        <a href="{{ url_for('security.register') }}" class="no-decoration">
          {{_ ("Sign up")}}
        </a>
      </div>
    {%- endif %}
    <div class="short-menu-right-button">
      <a href="{{url_for_security('login', next=request.path)}}" class="no-decoration">
          {{_ ("Log in")}}
      </a>
    </div>
  {%- else %}
    {%- if config.USERPROFILES %}
      <div class="short-menu-right-button">
        <div  id="user-profile-dropdown" class="ui floating dropdown computer only">
          <a href="{{ url_for('invenio_userprofiles.profile') }}" class="no-decoration">
            <i class="user icon"></i> {{ current_user.email }}
          </a>
          <div
            id="user-profile-menu"
            class="ui menu"
            role="menu"
            aria-labelledby="user-profile-dropdown-btn"
            >
            {%- for item in current_menu.submenu('settings').children if item.visible %}
              <a role="menuitem" class="item" href="{{ item.url }}" tabindex="-1">
                {{ item.text|safe }}
              </a>
            {%- endfor %}

            <div class="ui divider"></div>

            {% set ns = namespace(admin_menu=False) %}
            {%- for item in current_menu.submenu('profile-admin').children if item.visible %}
              {% set ns.admin_menu = True %}
              <a role="menuitem" class="item" href="{{ item.url }}" tabindex="-1">
                {{ item.text|safe }}
              </a>
            {%- endfor %}
            </div>
        </div>

        {# Mobile/Tablet Account menu #}
        <div class="sub-menu mobile tablet only">
          <a href="{{ url_for('invenio_userprofiles.profile') }}" class="no-decoration">
            <i class="user icon"></i> {{ current_user.email }}
          </a>
        </div>
      </div>
      <div class="short-menu-right-button">
        <a class="dropdown-item no-decoration" href="{{url_for_security('logout')}}">
          {{_('Sign out')}}
        </a>
      </div>
    {%- endif %}
  {%- endif %}
{%- endif %}

invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/login_user.html
{#
  Copyright (C) 2020-2025 Graz University of Technology.

  invenio-theme-tugraz is free software; you can redistribute it and/or
  modify it under the terms of the MIT License; see LICENSE file for more
  details.
#}

{% extends config.INVENIO_THEME_TUGRAZ_ACCOUNT_BASE %}

{% from "invenio_accounts/_macros.html" import render_field, form_errors %}
{%- from "invenio_oauthclient/_macros.html" import oauth_button %}

{% block page_body %}
  <div class="spacer-long"></div>
  <div class="spacer-long"></div>
  <div class="ui container">
    <div class="ui centered grid padded">
      <div class="ui padded segments large form">
        <div class="ui login segment padded">
          <div class="divider hidden"></div>

          {%- block form_header %}
            <h3 class="ui login header">{{ _('Log in to Repository') }}</h3>
          {%- endblock form_header %}

          <div class="ui divider"></div>
          <!--Log in with SSO-->
          {% if config.OAUTHCLIENT_REMOTE_APPS %}
            <div class="ui form">
              {% for name in config.OAUTHCLIENT_REMOTE_APPS.keys() %}
                {{ oauth_button(name, next=request.args.get('next')) }}
              {% endfor %}
            </div>
          {% endif %}
          {% set next_url=request.args.get('next') or request.referrer %}
          {% if config.SSO_SAML_IDPS %}
            {% for name in config.SSO_SAML_IDPS.keys() %}
              <div class="field">
                <a class="login-page-button ui fluid large button" href="{{ url_for('sso_saml.sso', idp=name, next=next_url) }}">
                  {{
                    _('Log in with %(title)s', title=config.SSO_SAML_IDPS[name]['title']|default("SAML", true))
                  }}
                  <img src="{{ url_for('static', filename=config.INVENIO_THEME_TUGRAZ_ICON) }}" height="20px" />
                </a>
              </div>
            {% endfor %}
          {% endif %}
          {% if config.EDUGAIN_LOGIN_ENABLED %}
            <div class="field">
              {% set return_url = url_for('invenio_edugain.authn_request', next=next_url, _external=True) %}
              <a class="login-page-button ui fluid large button" href="{{ url_for('invenio_edugain.login_discover', **{'return': return_url}) }}">
                {{ _('Log in with edugain') }}
                <img src="{{ url_for('static', filename='icons/eduGAIN-FavIcon-transparent.png') }}" height="20px" />
              </a>
            </div>
          {% endif %}
          {% if (config.OAUTHCLIENT_REMOTE_APPS or config.SSO_SAML_IDPS or config.EDUGAIN_LOGIN_ENABLED) and config.ACCOUNTS_LOCAL_LOGIN_ENABLED %}
            <div class="ui horizontal divider">
              {{ _("Or") }}
            </div>
          {% endif %}

          {%- block form_outer %}
            {%- if config.ACCOUNTS_LOCAL_LOGIN_ENABLED %}
              {%- with form = login_user_form %}
                {%- set accordion_active = "active" if form.errors else "" %}
                <div class="ui styled accordion">
                  <div class="title trigger {{ accordion_active }}">
                    {{ _('Log in with repository credentials') }}
                    <i class="user icon button"></i>
                  </div>
                  <div class="content {{ accordion_active }}">
                    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form" class="ui large form">
                      {{ form.hidden_tag() }}
                      {{ form_errors(form) }}
                      {{ render_field(form.email, icon="user icon", autofocus=True, errormsg=False) }}
                      {{ render_field(form.password, icon="lock icon", errormsg=False) }}
                      <button type="submit" class="ui fluid large submit button">
                        <i class="ui sign-in icon"></i>{{ _('Log In') }}
                      </button>
                    </form>
                  </div>
                </div>
              {%- endwith %}
            {%- endif %}
          {%- endblock form_outer %}

          <div class="divider hidden"></div>
        </div>

        {%- block registerable %}
          {%- if security.registerable %}
            <div class="ui primary segment padded text-muted">
              {% trans sitename=config.ACCOUNTS_SITENAME %}New to {{ sitename }}?{% endtrans %}
              <a href="{{ url_for_security('register', next=request.args.get('next')) }}">{{ _('Sign up') }}</a>
            </div>
          {%- endif %}
        {%- endblock registerable %}

        {%- block recoverable %}
          {%- if security.recoverable %}
            <div class="ui basic segment padded">
              <a class="ui inverted header tiny"
                href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password?') }}</a>
            </div>
          {%- endif %}
        {%- endblock recoverable %}

      </div>
    </div>
  </div>
{% endblock page_body %}

invenio_theme_tugraz/templates/invenio_theme_tugraz/base.html
{#
  Copyright (C) 2020-2023 Graz University of Technology.

  invenio-theme-tugraz is free software; you can redistribute it and/or
  modify it under the terms of the MIT License; see LICENSE file for more
  details.
#}

<!DOCTYPE html>
<html lang="{{ current_i18n.locale.language|safe }}" dir="{{ current_i18n.locale.text_direction }}">
  <head>
    {%- block head %}
      {%- block head_meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {%- if description %}
          <meta name="description" content="{{ description }}" />
        {% endif %}

        {%- if keywords %}
          <meta name="keywords" content="{{ keywords }}" />
        {% endif %}

        {%- if config.get("THEME_GOOGLE_SITE_VERIFICATION", None) %}
          {%- for google_id in config.THEME_GOOGLE_SITE_VERIFICATION %}
            <meta name="google-site-verification" content="{{google_id}}"/>
          {%- endfor %}
        {%- endif %}
      {%- endblock head_meta %}

      {%- block head_title %}
        {%- set title = title or _(config.THEME_SITENAME) or _("Invenio") %}
        <title>{{title}}</title>
      {%- endblock head_title %}

      {%- block head_links %}
        <link rel="shortcut icon" href="{{ url_for("static", filename="favicon.ico") }}"/>

        {%- if keywords %}
          <link rel="canonical" href="{{ canonical_url }}"/>
        {% endif %}

        {%- block head_links_langs %}
          {%- if alternate_urls %}
            {%- for alt_ln, alternate_url in alternate_urls.items() %}
              <link rel="alternate" hreflang="{{ alt_ln }}" href="{{ alternate_url }}"/>
            {%- endfor %}
          {%- endif %}
        {%- endblock %}
      {%- endblock head_links %}

      {%- block header %}{% endblock header %}

      {%- block css %}
        {{ webpack["theme.css"] }}
        {{ webpack["invenio-theme-tugraz-theme.css"] }}
      {%- endblock css %}
    {%- endblock head %}
  </head>

  <body itemscope itemtype="http://schema.org/WebPage" data-spy="scroll" data-target=".scrollspy-target">
    {%- block body %}
      {%- block browserupgrade %}
        <!--[if lt IE 10]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
      {%- endblock browserupgrade %}

      {%- block body_inner %}
        {%- block page_header %}
          {% include config.THEME_HEADER_TEMPLATE %}
        {%- endblock page_header %}

        {%- block page_body %}
          {% include "invenio_theme/body.html" %}
        {%- endblock page_body %}

        {%- block page_footer %}
          {% include config.THEME_FOOTER_TEMPLATE %}
        {%- endblock page_footer %}
      {%- endblock body_inner %}

      {%- block javascript %}
        {% include config.THEME_JAVASCRIPT_TEMPLATE %}
      {%- endblock javascript %}

      {%- block trackingcode %}
        {% include config.THEME_TRACKINGCODE_TEMPLATE %}
      {%- endblock %}
    {%- endblock body %}
  </body>
</html>

invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html
{#
  Copyright (C) 2020-2023 Graz University of Technology.

  invenio-theme-tugraz is free software; you can redistribute it and/or
  modify it under the terms of the MIT License; see LICENSE file for more
  details.
#}

{% if not config.THEME_TUGRAZ_PRODUCTION %}
  <div class="ui sticky test-instance">
    <h4>{{ _("Test Instance") }}</h4>
    <p>{{ _("This is the test instance of the TU Graz Repository.") }}</p>
  </div>
{% endif %}

<div>
  <header>
    {%- block site_banner %}
      {% from 'invenio_banners/banner.html' import banner %}
      {{ banner() }}
    {%- endblock site_banner %}

    {%- block navbar %}
      <nav>
        {%- block navbar_header %}
          {%- include "invenio_theme_tugraz/navbar.html" %}
        {%- endblock navbar_header %}

        <div class="ui container">
          <div class="ui grid stackable container">
            <div class="three column row centered" style="padding-bottom: 0;">
              <div class="two wide column main-menu-entry">
                <a href="{{url_for('invenio_theme_tugraz.index')}}" title="Home" class="no-decoration">
                  <span class="home-inline">
                    <svg shape-rendering="geometricPrecision" id="int-menu-q-home-icon"
                         xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg"
                         version="1.1" xml:space="preserve" height="36.997" width="35.969"
                         enable-background="new 0 0 595.28 841.89" y="0px" x="0px" xmlns:cc="http://creativecommons.org/ns#"
                         xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 35.969 36.997451">
                         <polyline style="stroke:#E4154B;stroke-linecap:square;stroke-width:4;fill:none"
                                   points="282.72 437.28 282.72 414.77 297.71 406.69 312.69 414.77 312.69 437.28"
                                   transform="translate(-279.72 -403.28)">
                         </polyline>
                    </svg>
                    {{ _("Home") }}
                  </span>
                </a>
              </div>

              <div class="two wide column main-menu-entry">
                <a role="menuitem" href="/communities" class="no-decoration">{{ _("Communities") }}</a>
              </div>
              <div class="two wide column main-menu-entry">
                <a role="menuitem" href="/me/overview" class="no-decoration">{{ _("Dashboard") }}</a>
              </div>
            </div>

            <div id="margin-divider" class="ui divider main-menu-underline-line">

            </div>
          </div>

          <div class="spacer"></div>
        </div>

      </nav>
    {%- endblock navbar %}

    {%- block flashmessages %}
      {%- from "invenio_theme/macros/messages.html" import flashed_messages with context -%}
      {{ flashed_messages() }}
    {%- endblock %}
  </header>
</div>

invenio_theme_tugraz/templates/invenio_theme_tugraz/navbar.html
{#
  Copyright (C) 2020-2023 Graz University of Technology.

  invenio-theme-tugraz is free software; you can redistribute it and/or
  modify it under the terms of the MIT License; see LICENSE file for more
  details.
#}

{% set options = [
  {
    "key": "records",
    "text": _("All"),
    "value": url_for("invenio_search_ui.search"),
    "title": "repo",
  },{
    "key": "rdm",
    "text": _("Research Results"),
    "value": "/records/search",
    "title": "Research Data",
  },{
    "key": "marc21",
    "text": _("Publications"),
    "value": url_for("invenio_records_marc21.search"),
    "title": "publication",
  },{
    "key": "lom",
    "text": _("Educational Resources"),
    "value": url_for("invenio_records_lom.search"),
    "title": "oer",
  }
]
%}

<div class="ui container">
  <div class="short-menu" id="all-menu-top-table">
    <div class="short-menu-left">
      <div id="all-menu-top-left-item">
        <div class="short-menu-left-search">
          <div style="display: inline-block;">
            <div class="item p-0 search-bar rel-mr-1">
              <div id="header-search-bar" data-options='{{ options | tojson }}'></div>
            </div>
          </div>

          <div class="short-menu-left-lang">
            {%- for l in current_i18n.get_locales() %}
              {%- if current_i18n.language != l.language %}
                <a href="{{ url_for("invenio_i18n.set_lang", lang_code=l.language) }}"
                   class="no-decoration">
                  {{ l.get_display_name().upper()[0:2] }}
                </a>
              {%- endif %}
            {%- endfor %}
          </div>
        </div>
      </div>
    </div>

    <div class="short-menu-right">
      {%- block navbar_right %}
        {%- include config.THEME_HEADER_LOGIN_TEMPLATE %}
      {%- endblock navbar_right %}
    </div>
  </div>


  <!----END MENU------------------------------------------------------------->

  <div class="ui grid" id="main-logo">
    <!-- Left -->
    <div class="left floated left aligned six wide column" id="repo-logo">
      <div class="inline-elements">
        <div class="repo-img">
          <img height="51.862" src="{{ url_for("static", filename="images/library_logo.png")}}">
        </div>
        <div class="affiliation-text">
          <a title="Home" href="{{url_for("invenio_theme_tugraz.index")}}" class="no-decoration">
            {{ _("TU GRAZ") }}
            <br>
            {{ _("REPOSITORY") }}
            <br>
            {{ _("LIBRARY & ARCHIVES") }}
          </a>
        </div>
      </div>
    </div>
    <!-- Right -->
    <div class="right floated right aligned six wide column">
      <div class="affiliation-logo" id="int-header-logo">
        <a href="https://www.tugraz.at" title="TU Graz Home" target="_blank" class="no-decoration">
          <div class="affiliation-logo-claim">
            <div class="affiliation-logo-claim-single">{{ _("SCIENCE") }}</div>
            <div class="affiliation-logo-claim-single">{{ _("PASSION") }}</div>
            <div class="affiliation-logo-claim-single">{{ _("TECHNOLOGY") }}</div>
          </div>
          {%- include "invenio_theme_tugraz/tu_graz_logo.svg" %}
        </a>
      </div>
    </div>
  </div>
</div>